# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: rower_development
  pool: 5
  username: przemek903
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rower_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
